# Generated by Django 5.0 on 2024-02-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_video',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Youtube video'),
        ),
    ]
