# Generated by Django 5.0 on 2024-02-26 08:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_project_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
    ]
