# Generated by Django 5.0 on 2024-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='description',
            field=models.TextField(blank=True, max_length=10000, verbose_name='description'),
        ),
    ]
