# Generated by Django 5.0 on 2024-02-26 10:27

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_information_youtube_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='description'),
        ),
        migrations.CreateModel(
            name='InformationLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='information.information', verbose_name='information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'information like',
                'verbose_name_plural': 'information likes',
            },
        ),
    ]
